# set up non-root bins 
LOCAL_BIN="$HOME/git/ongoing/toolbox/bin"
export GOPATH="$HOME/.local/share/applications/go"
GO_BIN="$GOPATH/bin"
export RUSTTEST="$HOME/.cargo"
CARGO_BIN="$HOME/.cargo/bin"
TOOLBOX_BIN="$HOME/git/ongoing/toolbox/bin"

# export PATH env. 
export PATH=$LOCAL_BIN:$GO_BIN:$CARGO_BIN:$TOOLBOX_BIN:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""


# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.dotfiles/zsh.d"


## @TODO: continue reviewing docs/github to see if better options available
## NOTE: zsh-bat overwrites "cat" with "bat" - use "rcat" to use old "cat"
plugins=(git zsh-autosuggestions you-should-use zsh-bat z git-extras tldr zsh-syntax-highlighting )

source $ZSH/oh-my-zsh.sh

# User configuration
#
export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
fi
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
export ZSH_CUSTOM="$HOME/.config/zsh.d"
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias gs='git status'
export DOTFILES_HOME="$HOME/.dotfiles"
alias gs='git status'




# ========================================================================
# 	THEME
# ========================================================================

fpath+=($HOME/.config/zsh/themes/pure)
autoload -U promptinit; promptinit

zstyle :prompt:pure:user color '#81A1C1'
zstyle :prompt:pure:host color '#81A1C1'
zstyle :prompt:pure:path color '#81A1C1'

zstyle :prompt:pure:prompt:success color green
zstyle :prompt:pure:git:branch color '#D8BFD8'
zstyle :prompt:pure:git:action color '#B48EAD'

zstyle :prompt:pure:git:dirty color red 

zstyle :prompt:pure:git:arrow color green
zstyle :prompt:pure:git:stash show yes
zstyle :prompt:pure:git:stash color magenta

prompt pure

# syntax hl - needs to be at end of file 
# source ~/.dotfiles/zsh.d/plugins/zsh-syntax-highlighting.zsh


# ========================================================================
# 	ALIASES
# ========================================================================

# Temporary location for git aliases while I work/test on submodule code
# Keep aliases confined to this section to simplify any future/
# code migrating 


## WORKFLOW ALIASES WIP
alias gs="git status"
alias gcb="git checkout -b "
alias gcmn="git checkout main "
alias gcmt="git commit -m "
alias gcmn="git checkout main "
alias grb="git rebase -i HEAD~$1"
alias grb2='git rebase -i HEAD~'"$1"
alias ga="git add"
alias gpl="git pull "
alias gp="git push "
alias gpf="git push --force "
alias gdf="git diff "
alias gdfm="git diff main"
alias gdfh="git diff HEAD~1"
alias gdfs="git diff --staged "
alias zsrc="source $HOME/.zshrc "
alias grs="git restore "$1
alias grss="git restore --staged "

