"" source vimrc modules 

" trying hack
source $HOME/.dotfiles/vim.d/plug.vimrc
source $HOME/.dotfiles/vim.d/general.vimrc
source $HOME/.dotfiles/vim.d/leader.vimrc
source $HOME/.dotfiles/vim.d/functions.vimrc
source $HOME/.dotfiles/vim.d/plugins.vimrc
